#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import csv

# (dia, titulo, categoria, duracao_min, dificuldade, tema_central, gancho_inicial, roteiro_completo)
R = [
# ---------- Semana 1 — Fundamentos ----------
(1,"Apresenta-te em 15 segundos","Reels",20,"fácil",
 "Um Reel de apresentação que diz quem és, para quem trabalhas e o que a pessoa ganha em seguir-te.",
 "Se chegaste agora ao meu perfil, isto é para ti.",
 "[0-3s] Olha para a câmara: 'Se chegaste agora, deixa-me apresentar-me.' [3-8s] Diz o teu nome + o que fazes + para quem. [8-12s] Mostra 1 resultado ou promessa concreta. [12-15s] CTA: 'Segue para aprenderes a crescer no Instagram com método.'"),
(2,"Como escolher o teu nicho sem te limitares","Carrossel",30,"média",
 "Ajudar quem tem medo de escolher um nicho a encontrar um foco que não o prenda.",
 "Escolher um nicho não é uma prisão — é uma direção.",
 "Slide 1: 'Tens medo de escolher um nicho?' Slide 2: o erro de tentar falar para toda a gente. Slide 3: a fórmula (o que amas x o que sabes x o que resolve). Slide 4: como testar sem te fechares. Slide 5: exemplo prático. Slide 6: CTA 'Guarda e volta quando tiveres dúvidas.'"),
(3,"O erro que trava o teu crescimento","Reels",25,"média",
 "Nomear o erro de focar em quantidade em vez de intenção, e dar a solução em 3 passos.",
 "Postas todos os dias e mesmo assim não cresces? O problema não é a quantidade.",
 "[0-3s] Gancho: 'Postas todos os dias e não cresces...' [3-8s] Nomeia o erro: criar para o algoritmo, não para uma pessoa. [8-18s] 3 passos: escreve para 1 pessoa; começa pela dor dela; 1 Reel = 1 ideia. [18-25s] CTA: 'Guarda e aplica no próximo vídeo.'"),
(4,"Bastidores: um dia na tua vida de criadora","Stories",10,"fácil",
 "Aproximar a audiência mostrando os bastidores reais do teu dia.",
 "Vem comigo num dia normal.",
 "Story 1: bom dia + o que vais fazer hoje. Story 2: bastidores da gravação. Story 3: um perrengue real. Story 4: enquete 'querem ver mais assim?'. Story 5: fecho com o resultado do dia."),
(5,"3 ganchos que travam o scroll","Reels",25,"média",
 "Ensinar 3 modelos de gancho que prendem nos primeiros 3 segundos.",
 "Os teus vídeos não têm poucas views — têm um mau começo.",
 "[0-3s] 'O teu vídeo não tem poucas views, tem um mau começo.' [3-20s] Mostra 3 ganchos: 1) 'Se fazes X, para de fazer Y'; 2) 'Ninguém te disse isto sobre...'; 3) 'Fiz X durante 30 dias e...'. [20-25s] CTA: 'Testa um destes hoje e diz-me nos comentários.'"),
(6,"Otimiza a tua bio em 5 passos","Carrossel",25,"fácil",
 "Transformar a bio numa montra clara: o que fazes, para quem e o próximo passo.",
 "A tua bio decide se te seguem em 3 segundos.",
 "Slide 1: 'A tua bio tem 3 segundos para convencer.' Slide 2: diz o que fazes. Slide 3: para quem. Slide 4: uma chamada à ação (↓). Slide 5: exemplo antes/depois. Slide 6: CTA 'Copia a estrutura.'"),
(7,"Antes e depois do teu perfil","Reels",25,"média",
 "Mostrar uma transformação de perfil para inspirar e provar método.",
 "Foi assim que transformei este perfil em semanas.",
 "[0-3s] Mostra o 'antes' do perfil. [3-12s] Aponta 3 problemas (foto, bio, feed). [12-20s] Mostra o 'depois' e o que mudou. [20-25s] CTA: 'Queres o teu antes/depois? Comenta MAPA.'"),
(8,"A tua história em 30 segundos","Reels",30,"média",
 "Contar a tua origem de forma que crie ligação e autoridade.",
 "Nem sempre foi assim.",
 "[0-5s] 'Nem sempre foi assim.' Mostra o ponto de partida. [5-20s] O momento de virada + o que aprendeste. [20-28s] Onde estás hoje. [28-30s] CTA: 'Se te revês, segue para a próxima parte.'"),
(9,"Enquete: o que a tua audiência quer ver","Stories",10,"fácil",
 "Usar stories interativos para descobrir o que a audiência quer.",
 "Ajuda-me a decidir o próximo conteúdo.",
 "Story 1: 'Preciso da tua ajuda.' Story 2: enquete entre 2 temas. Story 3: caixa 'o que queres aprender?'. Story 4: mostra os resultados. Story 5: 'É feito, vou gravar isto.'"),
(10,"5 métricas que importam (e as que não)","Carrossel",30,"média",
 "Ensinar a olhar para as métricas certas em vez de likes de vaidade.",
 "Estás a olhar para os números errados.",
 "Slide 1: 'Likes não pagam contas.' Slide 2: alcance de não-seguidores. Slide 3: guardados. Slide 4: partilhas. Slide 5: visitas ao perfil. Slide 6: retenção. Slide 7: CTA 'Guarda para a próxima análise.'"),
# ---------- Semana 2 — Conteúdo com IA ----------
(11,"Como usar o ChatGPT para criar ganchos","Reels",25,"média",
 "Mostrar como pedir ganchos à IA e escolher o melhor.",
 "Deixa a IA escrever 10 ganchos por ti em 30 segundos.",
 "[0-3s] 'Ganchos em 30 segundos com IA.' [3-15s] Mostra o ecrã: 'Dá-me 10 ganchos para um Reel sobre X, no tom Y'. [15-22s] Escolhe 1 e adapta à tua voz. [22-25s] CTA: 'Salva o prompt no comentário fixo.'"),
(12,"As 4 IAs gratuitas que uso todos os dias","Carrossel",30,"fácil",
 "Apresentar ferramentas de IA gratuitas para criar conteúdo.",
 "Não precisas de pagar para criar com IA.",
 "Slide 1: 'IA de graça? Sim.' Slide 2: uma para ideias. Slide 3: uma para legendas. Slide 4: uma para imagens. Slide 5: uma para edição. Slide 6: CTA 'Guarda e experimenta uma hoje.'"),
(13,"Escreve uma legenda que vende com IA","Reels",25,"média",
 "Ensinar a estrutura de legenda persuasiva com ajuda da IA.",
 "A tua legenda também vende — se a escreveres assim.",
 "[0-3s] 'A legenda também vende.' [3-15s] Estrutura: gancho + dor + solução + CTA. Mostra a IA a preencher cada parte. [15-22s] Ajusta o tom. [22-25s] CTA: 'Comenta LEGENDA que envio o prompt.'"),
(14,"Mostra a IA a trabalhar por ti","Stories",10,"fácil",
 "Bastidores de como usas a IA no teu processo.",
 "Vem ver a IA a criar comigo.",
 "Story 1: 'A minha assistente é IA.' Story 2: mostra o prompt no ecrã. Story 3: o resultado. Story 4: como o adaptas. Story 5: enquete 'queres o prompt?'."),
(15,"Prompt perfeito: a fórmula em 4 partes","Carrossel",35,"difícil",
 "Ensinar uma estrutura de prompt para resultados melhores.",
 "Prompt mau, resultado mau. A culpa não é da IA.",
 "Slide 1: 'A IA só é tão boa quanto o teu pedido.' Slide 2: Papel ('age como...'). Slide 3: Contexto (para quem, tom). Slide 4: Tarefa (o que queres). Slide 5: Formato (como queres). Slide 6: exemplo completo. Slide 7: CTA 'Guarda a fórmula.'"),
(16,"Transforma 1 ideia em 7 Reels com IA","Reels",35,"difícil",
 "Mostrar como multiplicar uma ideia numa série de conteúdos.",
 "Uma ideia dá para uma semana inteira de conteúdo.",
 "[0-3s] '1 ideia = 7 Reels.' [3-20s] Pede à IA 7 ângulos diferentes do mesmo tema (erro, mito, passo a passo, história, comparação, lista, opinião). [20-30s] Mostra a lista pronta. [30-35s] CTA: 'Comenta SÉRIE que ensino o prompt.'"),
(17,"Deixa a IA planear a tua semana de conteúdo","Reels",25,"média",
 "Usar IA para montar um plano semanal de posts.",
 "Nunca mais olhes para a página em branco.",
 "[0-3s] 'Página em branco? Nunca mais.' [3-18s] Prompt: 'Cria-me um plano de 7 posts para X, com formato e gancho de cada'. Mostra o resultado. [18-25s] CTA: 'Salva e adapta ao teu nicho.'"),
(18,"10 prompts para ideias de Reels","Carrossel",30,"fácil",
 "Dar prompts prontos para nunca faltar ideias.",
 "Rouba estes 10 prompts.",
 "Slide 1: '10 prompts para ideias.' Slides 2-6: 2 prompts por slide (ex: 'lista os 5 erros mais comuns em X', 'que mito devo desmontar sobre Y'). Slide 7: CTA 'Guarda — vais precisar.'"),
(19,"IA para editar mais rápido","Reels",25,"média",
 "Mostrar ferramentas de IA que aceleram a edição.",
 "Edito um Reel em metade do tempo com isto.",
 "[0-3s] 'Edição em metade do tempo.' [3-18s] Mostra: legendas automáticas, cortes por IA, remoção de pausas. [18-25s] CTA: 'Qual usas? Comenta.'"),
(20,"Pergunta e resposta sobre IA","Stories",10,"fácil",
 "Responder a dúvidas comuns sobre usar IA no conteúdo.",
 "As tuas dúvidas sobre IA — respondidas.",
 "Story 1: caixa 'pergunta-me sobre IA'. Story 2-4: responde a 3 dúvidas frequentes. Story 5: 'guarda o perfil para não perderes.'"),
# ---------- Semana 3 — Formatos que crescem ----------
(21,"Tutorial rápido: ensina algo em 20s","Reels",25,"média",
 "Ensinar um micro-tutorial que gera guardados.",
 "Em 20 segundos ensino-te a fazer isto.",
 "[0-3s] Mostra o resultado final primeiro. [3-18s] Passo 1, 2, 3 rápidos com texto no ecrã. [18-20s] CTA: 'Guarda para fazeres depois.'"),
(22,"Lista: 5 dicas em 30 segundos","Reels",20,"fácil",
 "Formato de lista rápida, fácil de consumir e guardar.",
 "5 dicas que ninguém te deu.",
 "[0-3s] '5 dicas rápidas.' [3-25s] Uma dica a cada ~4s, com número no ecrã. [25-30s] CTA: 'Qual foi a tua favorita? Comenta o número.'"),
(23,"Passo a passo de um post viral","Carrossel",30,"média",
 "Dissecar a anatomia de um post que funcionou.",
 "Isto viralizou — e não foi por sorte.",
 "Slide 1: 'Porque é que este post bombou.' Slide 2: o gancho. Slide 3: a estrutura. Slide 4: o CTA. Slide 5: o timing. Slide 6: CTA 'Copia a estrutura.'"),
(24,"Bastidores da tua criação","Reels",20,"fácil",
 "Mostrar o processo por trás de um conteúdo.",
 "É isto que ninguém vê.",
 "[0-3s] 'O que ninguém vê.' [3-15s] Montagem dos bastidores (ideia, gravação, edição). [15-20s] CTA: 'Segue para veres o resultado final.'"),
(25,"Reage a um mito do teu nicho","Reels",25,"média",
 "Desmontar um mito comum para gerar debate.",
 "Isto que te ensinaram está errado.",
 "[0-3s] 'Isto que te ensinaram está errado.' [3-8s] Diz o mito. [8-20s] Explica porquê e o que é verdade. [20-25s] CTA: 'Concordas? Comenta.'"),
(26,"Antes vs depois (transformação)","Carrossel",30,"média",
 "Mostrar uma transformação passo a passo.",
 "Do zero ao resultado — vê como.",
 "Slide 1: o 'antes'. Slide 2: o problema. Slide 3-4: os passos. Slide 5: o 'depois'. Slide 6: CTA 'Guarda como inspiração.'"),
(27,"Responde à pergunta que mais te fazem","Reels",15,"fácil",
 "Responder à dúvida mais comum da audiência.",
 "A pergunta que mais me fazem é esta.",
 "[0-3s] 'A pergunta que mais me fazem...' [3-12s] Responde direto e claro. [12-15s] CTA: 'Tinhas esta dúvida? Comenta.'"),
(28,"Caixa de perguntas: tira dúvidas","Stories",10,"fácil",
 "Sessão de perguntas para aproximar e criar conteúdo.",
 "Hoje é dia de tirar dúvidas.",
 "Story 1: caixa de perguntas. Story 2-4: responde às melhores. Story 5: 'guarda estas respostas.'"),
(29,"Um dia de trabalho em 3 clips","Reels",25,"média",
 "Vlog curto e dinâmico do teu dia.",
 "O meu dia em 3 clips.",
 "[0-3s] 'O meu dia em 3 clips.' [3-20s] Manhã, tarde, noite — cortes rápidos com música. [20-25s] CTA: 'Como é o teu? Conta.'"),
(30,"Erros de principiante (e como evitar)","Carrossel",30,"média",
 "Listar erros comuns e as soluções.",
 "Eu cometi todos estes erros — tu não precisas.",
 "Slide 1: 'Os erros que eu cometi.' Slides 2-6: um erro + a solução por slide. Slide 7: CTA 'Guarda para não repetires.'"),
# ---------- Semana 4 — Autoridade e storytelling ----------
(31,"A lição que mudou o teu conteúdo","Reels",30,"média",
 "Partilhar uma lição transformadora com storytelling.",
 "Uma frase mudou a forma como crio.",
 "[0-5s] 'Uma frase mudou tudo.' [5-22s] Conta o contexto + a lição. [22-30s] CTA: 'Guarda esta ideia.'"),
(32,"A tua jornada em 6 slides","Carrossel",30,"média",
 "Contar a tua evolução para criar ligação.",
 "De onde vim para onde estou.",
 "Slide 1: o início. Slide 2: a dificuldade. Slide 3: a decisão. Slide 4: o processo. Slide 5: o resultado. Slide 6: CTA 'Se te inspirou, partilha.'"),
(33,"Conta um fracasso (e o que aprendeste)","Reels",30,"difícil",
 "Vulnerabilidade que gera confiança e autoridade.",
 "O meu maior erro ensinou-me isto.",
 "[0-5s] 'O meu maior erro...' [5-22s] Conta o que correu mal + o que mudou depois. [22-30s] CTA: 'Já passaste por isto? Comenta.'"),
(34,"Opinião polémica do teu nicho","Reels",25,"média",
 "Tomar uma posição forte para gerar debate saudável.",
 "Vou dizer o que ninguém tem coragem.",
 "[0-3s] 'Opinião impopular:' [3-18s] Diz a tua posição e justifica. [18-25s] CTA: 'Concordas ou discordas? Comenta.'"),
(35,"Mitos vs verdades","Carrossel",30,"fácil",
 "Separar mitos de verdades do teu nicho.",
 "Mito ou verdade?",
 "Slide 1: 'Mito ou verdade?' Slides 2-6: um mito por slide + a verdade. Slide 7: CTA 'Qual te surpreendeu? Comenta.'"),
(36,"Porque começaste (o teu porquê)","Reels",30,"média",
 "Partilhar a tua motivação para gerar identificação.",
 "Não comecei por dinheiro.",
 "[0-5s] 'Não comecei por dinheiro.' [5-22s] Conta o teu verdadeiro porquê. [22-30s] CTA: 'Qual é o teu? Conta-me.'"),
(37,"Partilha uma vitória de aluna/cliente","Stories",10,"fácil",
 "Prova social através de um resultado real.",
 "Olha o que uma aluna conseguiu.",
 "Story 1: 'Tenho de mostrar isto.' Story 2: o print/resultado. Story 3: o contexto. Story 4: 'orgulho.' Story 5: 'queres o mesmo? DM.'"),
(38,"3 coisas que gostava de saber antes","Reels",25,"média",
 "Conselhos ao teu 'eu' do passado.",
 "Se pudesse voltar atrás, dizia-me isto.",
 "[0-3s] 'Se voltasse atrás...' [3-20s] 3 conselhos, um a um. [20-25s] CTA: 'Guarda para o teu início.'"),
(39,"O método que uso (em 5 passos)","Carrossel",35,"difícil",
 "Apresentar o teu método como autoridade.",
 "É assim que faço — passo a passo.",
 "Slide 1: 'O meu método em 5 passos.' Slides 2-6: um passo por slide. Slide 7: CTA 'Guarda e aplica.'"),
(40,"Bastidores de uma conquista","Reels",25,"média",
 "Mostrar o esforço por trás de um marco.",
 "Por trás deste resultado houve muito trabalho.",
 "[0-3s] Mostra a conquista. [3-18s] Bastidores do esforço que ninguém viu. [18-25s] CTA: 'Continua, também vais chegar lá.'"),
# ---------- Semana 5 — Vender no Instagram ----------
(41,"Apresenta a tua oferta sem parecer venda","Reels",30,"difícil",
 "Vender através de valor, não de pressão.",
 "Vender não é empurrar — é mostrar o caminho.",
 "[0-3s] 'Vender não é empurrar.' [3-20s] Mostra o problema que resolves + como a tua oferta ajuda. [20-30s] CTA suave: 'Se é para ti, sabes onde estou.'"),
(42,"Como sei que isto é para ti","Carrossel",30,"média",
 "Ajudar a audiência a auto-identificar-se com a oferta.",
 "Isto é para ti se...",
 "Slide 1: 'Isto é para ti se...' Slides 2-5: sinais de identificação. Slide 6: o que vais ganhar. Slide 7: CTA 'Comenta EU QUERO.'"),
(43,"Sequência de venda em 5 stories","Stories",20,"difícil",
 "Estrutura de venda em stories que converte.",
 "Vou mostrar-te uma coisa em 5 stories.",
 "Story 1: o problema. Story 2: a virada. Story 3: a oferta. Story 4: a prova. Story 5: CTA com link/DM."),
(44,"Quebra a objeção mais comum","Reels",25,"média",
 "Responder à maior razão pela qual não compram.",
 "'Não tenho tempo' — deixa-me responder a isso.",
 "[0-3s] Diz a objeção. [3-18s] Responde com empatia + solução. [18-25s] CTA: 'Se era a tua dúvida, fala comigo.'"),
(45,"Resultados reais (prova social)","Carrossel",30,"média",
 "Mostrar provas concretas para gerar confiança.",
 "Não acredites em mim — olha os resultados.",
 "Slide 1: 'Resultados reais.' Slides 2-5: prints/depoimentos. Slide 6: CTA 'Queres ser o próximo? DM.'"),
(46,"Chama à ação: fecha por DM","Reels",25,"média",
 "Direcionar a audiência para a conversa que vende.",
 "Queres começar? É simples.",
 "[0-3s] 'Queres começar hoje?' [3-15s] Explica o próximo passo simples. [15-25s] CTA: 'Comenta EU QUERO e eu falo contigo.'"),
(47,"Bastidores da tua oferta","Stories",15,"fácil",
 "Mostrar o valor por dentro da tua oferta.",
 "Vem ver o que está por dentro.",
 "Story 1: 'O que está por dentro.' Story 2-4: mostra 3 partes da oferta. Story 5: 'quinta-feira abrem as vagas.'"),
(48,"Antes/depois de uma cliente","Reels",30,"média",
 "Contar a transformação de uma cliente.",
 "Ela estava aqui — hoje está aqui.",
 "[0-3s] Mostra o 'antes' da cliente. [3-18s] O processo + o 'depois'. [18-30s] CTA: 'Queres a tua transformação? DM.'"),
(49,"Perguntas frequentes sobre o teu serviço","Carrossel",30,"fácil",
 "Responder às dúvidas que travam a compra.",
 "As perguntas que mais me fazem sobre o meu trabalho.",
 "Slide 1: 'FAQ.' Slides 2-6: uma pergunta + resposta por slide. Slide 7: CTA 'Ficou alguma dúvida? DM.'"),
(50,"Escassez com verdade (última vaga)","Reels",25,"média",
 "Criar urgência genuína sem manipular.",
 "Faltam poucas vagas — e não é estratégia.",
 "[0-3s] 'Últimas vagas.' [3-15s] Explica porquê (limite real de acompanhamento). [15-25s] CTA: 'Se é agora, fala comigo hoje.'"),
# ---------- Semana 6 — Consistência e escala ----------
(51,"Como fazer 1 semana de conteúdo num dia","Reels",40,"difícil",
 "Ensinar a produzir em lote para ganhar tempo.",
 "Gravo uma semana de conteúdo num só dia.",
 "[0-3s] '1 dia = 1 semana de conteúdo.' [3-25s] Mostra o processo: planear, gravar em lote, editar em bloco. [25-40s] CTA: 'Comenta LOTE que ensino o método.'"),
(52,"Calendário de conteúdo simples","Carrossel",30,"média",
 "Dar uma estrutura simples de calendário semanal.",
 "Nunca mais postes sem plano.",
 "Slide 1: 'O teu calendário simples.' Slide 2: 1 Reel de crescimento. Slide 3: 1 carrossel de valor. Slide 4: stories diários. Slide 5: 1 conteúdo de venda. Slide 6: CTA 'Guarda e adapta.'"),
(53,"Reaproveita 1 vídeo em 3 formatos","Reels",25,"média",
 "Multiplicar 1 conteúdo em vários formatos.",
 "1 vídeo, 3 posts.",
 "[0-3s] '1 vídeo = 3 posts.' [3-18s] Mostra: Reel → carrossel → stories. [18-25s] CTA: 'Salva para reaproveitares.'"),
(54,"Cria uma série que fideliza","Reels",35,"difícil",
 "Ensinar a criar séries que fazem a audiência voltar.",
 "Séries fazem as pessoas voltarem — sempre.",
 "[0-3s] 'Séries viciam.' [3-22s] Como criar: um tema, um nome, um formato repetível. [22-35s] CTA: 'Que série queres ver? Comenta.'"),
(55,"Banco de ideias que nunca seca","Carrossel",30,"média",
 "Montar um sistema de ideias para nunca ficar sem conteúdo.",
 "Ideias não caem do céu — organizam-se.",
 "Slide 1: 'Nunca mais fiques sem ideias.' Slide 2: guarda perguntas da audiência. Slide 3: dúvidas de clientes. Slide 4: tendências do nicho. Slide 5: as tuas histórias. Slide 6: CTA 'Cria o teu banco hoje.'"),
(56,"Rotina de gravação sem stress","Reels",20,"fácil",
 "Mostrar uma rotina leve de gravação.",
 "Gravar não tem de ser um drama.",
 "[0-3s] 'Gravar sem stress.' [3-15s] Mostra a tua rotina simples (luz, telemóvel, guião). [15-20s] CTA: 'Qual é o teu maior bloqueio? Comenta.'"),
(57,"Mostra a tua consistência","Stories",10,"fácil",
 "Provar consistência para gerar confiança.",
 "Há X dias que apareço aqui.",
 "Story 1: 'Dia X seguido a aparecer.' Story 2: o que já mudou. Story 3: enquete 'notas diferença?'. Story 4: 'obrigada por estares aqui.'"),
(58,"O que fazer quando um Reel não vai","Reels",25,"média",
 "Tirar a pressão de um conteúdo que não performou.",
 "Um Reel fraco não te define.",
 "[0-3s] 'O Reel não foi? Calma.' [3-18s] 3 passos: analisa o gancho, não apagues, testa outro ângulo. [18-25s] CTA: 'Guarda para os dias difíceis.'"),
(59,"Checklist antes de publicar","Carrossel",25,"fácil",
 "Uma checklist rápida para publicar com qualidade.",
 "Antes de carregar em publicar, verifica isto.",
 "Slide 1: 'Checklist de publicação.' Slide 2: gancho forte? Slide 3: legenda com CTA? Slide 4: capa clara? Slide 5: hashtags/áudio? Slide 6: CTA 'Guarda e usa sempre.'"),
(60,"Celebra o teu progresso (marco)","Reels",20,"fácil",
 "Celebrar um marco para inspirar e humanizar.",
 "Chegámos aqui — e isto é só o começo.",
 "[0-3s] Anuncia o marco. [3-15s] Agradece + o que aprendeste no caminho. [15-20s] CTA: 'Obrigada por fazeres parte. Bora à próxima.'"),
]

with open("roteiros.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f, quoting=csv.QUOTE_MINIMAL)
    w.writerow(["dia","titulo","categoria","duracao_min","dificuldade","tema_central","gancho_inicial","roteiro_completo","videos_referencia"])
    for row in R:
        w.writerow(list(row) + [""])

print(f"OK — {len(R)} roteiros escritos em roteiros.csv")
